Detector for bad End of Stream Checks
spotbugs/spotbugs pull request #1581
Opened 2021-06-16 15:45 UTC by baloghadamsoftware

java.io.FileInputStream.read() and java.io.FileReader.read() both return an integer.
The value of this integer is -1 if the end of the stream is reached. Since
FileInputStream reads bytes and FileReader reads characters their return value
must be casted to these types. However, if the casting happens before the check
for -1 then -1 becomes indistinguishible from 0xFF in case of FileInputStream and
becomes Character.MAX_VALUE (the highest positive value of a character) in case
of FileReader. SEI CERT rule FIO08-J describes these bugs in detail. This patch adds
a new error message EOS_BAD_END_OF_STREAM_CHECK and a new detector
(FindBadEndOfStreamCheck) which checks for this kind of error.

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [X] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

2021-06-16 18:40 UTC, baloghadamsoftware commented
No new findings on the open-source projects we use for testing: [link](https://codechecker-demo.eastus.cloudapp.azure.com/java-static-analysis/reports?items-per-page=100&run=SpotBugs%20on%20MATSim-Libs%20%28user%3A%20spotbugs,%20branch%3A%20master%29&run=SpotBugs%20on%20SpotBugs%20%28user%3A%20spotbugs,%20branch%3A%20master%29&run=SpotBugs%20on%20Jenkins%20%28user%3A%20spotbugs,%20branch%3A%20master%29&run=SpotBugs%20on%20Bt%20%28user%3A%20spotbugs,%20branch%3A%20master%29&run=SpotBugs%20on%20Ttorrent%20%28user%3A%20spotbugs,%20branch%3A%20master%29&run=SpotBugs%20on%20NanoHTTPD%20%28user%3A%20spotbugs,%20branch%3A%20master%29&newcheck=SpotBugs%20on%20MATSim-Libs%20%28user%3A%20baloghadamsoftware,%20branch%3A%20FindBadEndOfStreamCheck%29&newcheck=SpotBugs%20on%20SpotBugs%20%28user%3A%20baloghadamsoftware,%20branch%3A%20FindBadEndOfStreamCheck%29&newcheck=SpotBugs%20on%20Jenkins%20%28user%3A%20baloghadamsoftware,%20branch%3A%20FindBadEndOfStreamCheck%29&newcheck=SpotBugs%20on%20Ttorrent%20%28user%3A%20baloghadamsoftware,%20branch%3A%20FindBadEndOfStreamCheck%29&newcheck=SpotBugs%20on%20Bt%20%28user%3A%20baloghadamsoftware,%20branch%3A%20FindBadEndOfStreamCheck%29&newcheck=SpotBugs%20on%20NanoHTTPD%20%28user%3A%20baloghadamsoftware,%20branch%3A%20FindBadEndOfStreamCheck%29). This is no wonder, these projects are quite mature and this kind of bug is more typical for novice Java programmers.

2021-06-16 23:13 UTC, ThrawnCA requested changes

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/FindBadEndOfStreamCheckTest.java
> +        BugInstanceMatcher bugInstanceMatcher = new BugInstanceMatcherBuilder()
Perhaps extract the bug instance assembly and check to a helper method, since several parts of it are repeated?

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs/etc/messages.xml
> +               java.io.FileReader.read() is converted before checking agains -1.</p>
Misspelled "against". Also, the word "output" or "return value" should be added before "is converted".

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs/etc/messages.xml
> +               Both methods return an int. If this int is converted to byte (in case of
"in case of" -> "in the case of"

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs/etc/messages.xml
> +               If it is converted to char (in case of FileReader.read()) then -1 becomes
"in case of" -> "in the case of"

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs/etc/messages.xml
> +      Th method java.io.FileInputStream.read() returns an int. If this int is converted to a byte then -1 (which
Misspelled "The".

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs/etc/messages.xml
> +  <BugCode abbrev="EOS">Bad End of Stream  check</BugCode>
Extra space.

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindBadEndOfStreamCheck.java
> + * FindBugs - Find bugs in Java programs
This should be "SpotBugs" since it never existed in FindBugs, and the University of Maryland has no claim on it.

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindBadEndOfStreamCheck.java
> +            if (value != null && value instanceof Integer && ((Integer) value).intValue() == 0) {
The `instanceof` check makes the null check redundant.

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindBadEndOfStreamCheck.java
> +                    || !("Ljava/io/FileInputStream;".equals(method.getClassDescriptor().getSignature())
Could extract `method.getClassDescriptor().getSignature()` to a local variable. Possibly even extract all this logic to a helper like `isFileRead(Method method)`.

2021-06-16 23:13 UTC, ThrawnCA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindBadEndOfStreamCheck.java
> +            if (value != null && value instanceof Integer && ((Integer) value).intValue() == -1) {
`instanceof` check makes null check redundant.

2021-06-23 23:02 UTC, ThrawnCA submitted a review, later dismissed

2021-06-24 22:44 UTC, ThrawnCA approved these changes

2021-07-02 06:07 UTC, KengoTODA requested changes

2021-07-02 06:07 UTC, KengoTODA commented on CHANGELOG.md
> +* New detector `FindBadEndOfStreamCheck` for new bug type `EOS_BAD_END_OF_STREAM_CHECK`. This bug is reported whenever the return value of java.io.FileInputStream.read() or java.io.FileReader.read()
Could you move this line to the bottom of `## Unreleased`? Then I'll merge and will be released as a part of the next release, probably `4.4.0`.

2021-07-02 06:18 UTC, KengoTODA commented on CHANGELOG.md
> +* New detector `FindBadEndOfStreamCheck` for new bug type `EOS_BAD_END_OF_STREAM_CHECK`. This bug is reported whenever the return value of java.io.FileInputStream.read() or java.io.FileReader.read()
To ease the merge process I tried to create a branch to merge both PRs in batch: https://github.com/spotbugs/spotbugs/compare/PR-from-baloghadamsoftware 
However, I used squashed commit so it loses author Infos in the commit. I will try another way without squash, but if you're OK to update your PRs, please update yours one by one.

2021-07-02 08:54 UTC, KengoTODA commented on CHANGELOG.md
> +* New detector `FindBadEndOfStreamCheck` for new bug type `EOS_BAD_END_OF_STREAM_CHECK`. This bug is reported whenever the return value of java.io.FileInputStream.read() or java.io.FileReader.read()
also created https://github.com/spotbugs/spotbugs/compare/PR-from-balonghadam2 with no squash commit, but its commit history seems non intuitive... I'll wait @baloghadamsoftware's conflict resolve.

2021-07-05 10:25 UTC, baloghadamsoftware commented
@KengoTODA Rebasing done, also moved line in CHANGELOG.md to ###Unreleased.

2021-07-06 01:27 UTC, KengoTODA approved these changes
Thanks for your PR!

2021-07-06 01:28 UTC, merged