fix: MutableClasses: net classes are in java.net
spotbugs/spotbugs pull request #1654
Opened 2021-08-20 13:30 UTC by candrews

URI, Inet4Address, and InetSocketAddress are in the java.net package, not java.util

Fixes #1653

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [ ] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

2021-08-22 22:25 UTC, ThrawnCA approved these changes

2021-08-23 00:09 UTC, KengoTODA requested changes
Please add an entry into `CHANGELOG.md`. We use https://keepachangelog.com/en/1.0.0/ so what you need is a `Fixed` type entry.

2021-08-23 00:22 UTC, candrews commented
> Please add an entry into `CHANGELOG.md`. We use https://keepachangelog.com/en/1.0.0/ so what you need is a `Fixed` type entry.

I've added a commit to this PR that updates `CHANGELOG.md`

Thank you for the review!

2021-08-23 03:13 UTC, KengoTODA approved these changes

2021-08-23 04:16 UTC, merged