Classes annotated with @Immutable or @jdk.internal.ValueBased are considered as immutable
spotbugs/spotbugs pull request #1676
Opened 2021-09-01 14:06 UTC by baloghadamsoftware

Partial fix for issue [#1601](https://github.com/spotbugs/spotbugs/issues/1601\)

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [X] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

2021-09-02 02:37 UTC, ThrawnCA approved these changes

2021-09-06 01:41 UTC, ThrawnCA approved these changes

2021-09-07 01:01 UTC, KengoTODA requested changes
Please resolve the conflict and push updated branch.

2021-09-07 11:03 UTC, KengoTODA submitted a review, later dismissed

2021-09-07 11:05 UTC, KengoTODA approved these changes

2021-09-07 11:18 UTC, merged

2022-07-15 14:46 UTC, kishore25kumar commented
@baloghadamsoftware Hey I tried to add the annotation com.google.errorprone.annotations.Immutable to one of my classes which findbugs is throwing false negative. But even after adding the annotation it is still not working. According to the code it should work when Immutable interface exists. Is my understanding correct?