Check for binary class name in annotation check
spotbugs/spotbugs pull request #1706
Opened 2021-09-14 22:07 UTC by rovarga

We are referencing Class file entries, hence type names use slashes.

Signed-off-by: Robert Varga <robert.varga@pantheon.tech>

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [ ] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

2021-09-14 23:23 UTC, ThrawnCA submitted a review, later dismissed

2021-09-15 07:54 UTC, KengoTODA requested changes
@rovarga could you resolve conflicts?

2021-09-15 15:34 UTC, rovarga commented
> @rovarga could you resolve conflicts?

Yup, should be ready again.

2021-09-16 01:18 UTC, KengoTODA approved these changes

2021-09-16 01:18 UTC, merged