Stop using local Eclipse as a part of dependency
spotbugs/spotbugs pull request #1902
Opened 2022-01-05 06:57 UTC by KengoTODA

This change makes it possible to build Eclipse plugins without local Eclipse IDE.
It is also possible to use metadata of artifacts (pom.xml) to maintain license, vulnerability, and version of dependencies.

close #1868

2022-01-05 08:11 UTC, KengoTODA commented on spotbugs/build.gradle
> +  }
These config will keep SpotBugs away from buggy logging libraries.
https://blog.gradle.org/log4j-vulnerability

2022-01-05 13:06 UTC, iloveeclipse commented on spotbugs/build.gradle
> +  }
I'm on it. I see few issues with Eclipse support also before this patch (wrong JLS settings, duplicated classpath elements, not compilable code, Java 11 dependencies introduced).

2022-01-05 22:52 UTC, ThrawnCA submitted a review, later dismissed

2022-01-06 16:35 UTC, iloveeclipse commented
I see following during the build:
```
> Task :buildSrc:compileKotlin
'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
```
I don't know why do we compile now kotlin, but that should probably also use Java 11.

Note: as I've mentioned before, Eclipse plugin code already depends on java 11 API but is compiled against Java 8. I will most likely want to change that to Java 11, and also increase minimal supported Eclipse SDK version to 4.15 (that works fine with Java 11). 

In general, for all spotbugs artifacts except annotations we should switch to Java 11, compiling with Java 8 JLS against Java 11 API and silently depending on Java 11 API's isn't a good idea anyway.

Another set of warnings related to Eclipse site generation:

```
> Task :eclipsePlugin:siteHtml
Execution optimizations have been disabled for task ':eclipsePlugin:siteHtml' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/data/git/spotbugs/eclipsePlugin/build/site/eclipse'. Reason: Task ':eclipsePlugin:pluginCandidateJar' uses this output of task ':eclipsePlugin:siteHtml' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/data/git/spotbugs/eclipsePlugin/build/site/eclipse'. Reason: Task ':eclipsePlugin:testPluginJar' uses this output of task ':eclipsePlugin:siteHtml' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

This is shown for
- eclipsePlugin:siteXml
- eclipsePlugin:siteHtml
- eclipsePlugin:pluginDailyJar
- eclipsePlugin:pluginStableLatestJar

Similar warnings are reported for
```
> Task :spotbugs:spotbugsGui
Execution optimizations have been disabled for task ':spotbugs:spotbugsGui' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/data/git/spotbugs/spotbugs/build/libs/spotbugs.jar'. Reason: Task ':spotbugs:spotbugsGui' uses this output of task ':spotbugs:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :spotbugs:spotbugsGuiTest
Execution optimizations have been disabled for task ':spotbugs:spotbugsGuiTest' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/data/git/spotbugs/spotbugs/build/libs/spotbugs.jar'. Reason: Task ':spotbugs:spotbugsGuiTest' uses this output of task ':spotbugs:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :spotbugs:spotbugsMain
Execution optimizations have been disabled for task ':spotbugs:spotbugsMain' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/data/git/spotbugs/spotbugs/build/libs/spotbugs.jar'. Reason: Task ':spotbugs:spotbugsMain' uses this output of task ':spotbugs:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :spotbugs:spotbugsTest
Execution optimizations have been disabled for task ':spotbugs:spotbugsTest' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/data/git/spotbugs/spotbugs/build/libs/spotbugs.jar'. Reason: Task ':spotbugs:spotbugsTest' uses this output of task ':spotbugs:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
SpotBugs ended with exit code 1
```

2022-01-06 16:45 UTC, iloveeclipse commented on spotbugs/build.gradle
> -def copyLibsForEclipse = tasks.register('copyLibsForEclipse', Copy) {
This makes Eclipse build unhappy. Since there are no libraries available for Eclipse, I can't compile / run SpotBugs from Eclipse anymore.

2022-01-06 19:45 UTC, iloveeclipse requested changes
I'm unable to get this build running producing correct eclipse configuration files.
This is partly due already existing issues, but partly because of removed .libs below.
I will try to push a commit to this branch that first fixes Eclipse config file generation.

2022-01-07 03:45 UTC, KengoTODA commented
Really thank you for your review!

About the Gradle warning around the build optimization, I will handle them in another ticket #1911.
About the target Eclipse version to support, I agree to change the minimal supported version to 4.12.0. I will change the [Eclipse version in CI](https://github.com/spotbugs/spotbugs/blob/fa0ef8ebb0c15edcd75b71d6b4218bafec6c3816/.github/workflows/build.yml#L23) later.

About the target Java version to support, I think it's not so good to drop Java 8 support for now (I personally believe that everyone should migrate to Java 17 asap, tho). Would be better to do it as a part of next major release.

About the `copyLibsForEclipse` task, I prefer removing it to handle dependencies not as files but as dependency with metadata (pom.xml). I will try to find a better way.  
Can I assume that we use the `eclipse` task to generate Eclipse projects? Or it is also OK to use `Import existing Gradle project` provided by the Eclipse itself.

2022-01-07 03:45 UTC, KengoTODA commented
personal note: working on 06c018828f91ae910d4d4ed8a854cf669fceaa06 to fix generated `.classpath` file

2022-01-07 09:27 UTC, iloveeclipse commented
> Can I assume that we use the eclipse task to generate Eclipse projects? 

Sure.

> Or it is also OK to use Import existing Gradle project provided by the Eclipse itself

No, this functionality is not available in default SDK, so this will be not OK.

2022-01-07 19:09 UTC, iloveeclipse commented
I've just switched to my Windows notebook (no Java 17, only Java 11) and see that for some reason both eclipsePlugin-junit and eclipsePlugin-test projects have classpath errors in Eclipse - they have such (fully wrong because unneeded) ´pdebuild.jar` library added: 

```
<classpathentry kind="lib" path="C:/git/spotbugs/eclipsePlugin-junit/build/pdeTool/pdebuild.jar">
```
Not sure why I didn't saw this on my Linux workstation.
I have no idea why that should be on classpath at all, this is coming from the new eclipse-convention.gradle.kts fie.

2022-01-09 23:25 UTC, ThrawnCA commented
> I think it's not so good to drop Java 8 support for now

Yeah, OpenJDK 8 is still supported until 2026, so there could be a lot of organisations not in a hurry to migrate, and that's okay.

2022-01-09 23:57 UTC, ThrawnCA approved these changes

2022-01-15 14:01 UTC, iloveeclipse commented
So with #1914 fixed we are able to build spotbugs core on Java 8, so I've reverted Java 11 changes on production projects and pushed updated commits that make also spotbugs developing & debugging in Eclipse and on Windows happy. For me this state works fine & is a clear improvement over the old one.

2022-01-25 13:12 UTC, iloveeclipse approved these changes

2022-01-25 13:12 UTC, merged