Report bug `SA_FIELD_SELF_ASSIGNMENT` in nested classes as well
spotbugs/spotbugs pull request #2161
Opened 2022-09-01 16:21 UTC by baloghadamsoftware

Bug `SA_FIELD_SELF_ASSIGNMENT` was not reported in nested classes, only in the outer class. This lead to inconsistent behavior. See issue ([#2142](https://github.com/spotbugs/spotbugs/issues/2142)). This PR fixes this issue.

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [X] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

2022-09-01 21:57 UTC, KengoTODA requested changes

2022-09-01 21:57 UTC, KengoTODA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindFieldSelfAssignment.java
> +                                        && third.getUserValue() instanceof Integer
Is instance is an `Integer`, we're sure that it is not-null.

```suggestion
                                || (loadedFromRegister2 >= 0 && third.getUserValue() instanceof Integer
```

2022-09-01 21:57 UTC, KengoTODA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindFieldSelfAssignment.java
> +                                        && loadedFromRegister2 == (Integer) third.getUserValue()))
Better to do not depends on auto boxing.
```suggestion
                                        && loadedFromRegister2 == ((Integer) third.getUserValue()).intValue()))
```

2022-09-01 21:57 UTC, KengoTODA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindFieldSelfAssignment.java
> +        if (seen == Const.GETFIELD && parentInstanceLoadFromRegister > -1) {
Could you replace this magic number `-1` with a `static final int` field?
Better to tell our intention to who is reading our code.

2022-09-01 21:57 UTC, KengoTODA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindFieldSelfAssignment.java
> +            top.setUserValue(parentInstanceLoadFromRegister);
when you use `UserValue` in your detector, please annotate the detector with `@CustomUserValue`.

refs https://blog.kengo-toda.jp/entry/2013/10/13/011552

2022-09-02 09:41 UTC, baloghadamsoftware commented
Thank you for your comments, @KengoTODA! I think I fixed every one of them now.

2022-09-03 13:30 UTC, KengoTODA approved these changes
LGTM, thank you!

2022-09-04 23:17 UTC, ThrawnCA submitted a review, later dismissed

2022-09-05 03:00 UTC, KengoTODA approved these changes

2022-09-05 03:00 UTC, merged