Fix of detector `DontUseFloatsAsLoopCounters` to prevent false positives
spotbugs/spotbugs pull request #2167
Opened 2022-09-06 11:09 UTC by baloghadamsoftware

Bug `FL_FLOATS_AS_LOOP_COUNTERS` was reported for several cases where floating-point types appear in the loops but not as loop counters. See issue ([#2126](https://github.com/spotbugs/spotbugs/issues/2126)).

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [X] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

2022-09-06 11:50 UTC, baloghadamsoftware commented
The build failure is not caused by this PR. Also `master` fails on the same test (`Issue2145`). Yesterday it was OK, and this test was added 3 weeks ago so the bug should be somewhere between yesterday's and today's commits.

2022-09-06 22:40 UTC, ThrawnCA requested changes

2022-09-06 22:40 UTC, ThrawnCA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/DontUseFloatsAsLoopCounters.java
> +        if (!FLOAT_STORERS.contains(getPrevOpcode(1))) {
"if not...else" is a double negative, perhaps refactor.

2022-09-06 22:40 UTC, ThrawnCA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/DontUseFloatsAsLoopCounters.java
> +    private static final Map<Integer, Integer> FLOAT_LOADERS = new HashMap<>();
Perhaps initialise this inside the `static` block, with a `Collections.unmodifiableMap`?

2022-09-06 22:40 UTC, ThrawnCA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/DontUseFloatsAsLoopCounters.java
> +    private static final Map<Integer, Integer> FLOAT_CONSTANT_PUSHERS = new HashMap<>();
Perhaps wrap in `Collections.unmodifiableMap`?

2022-09-08 22:44 UTC, ThrawnCA approved these changes

2022-09-09 01:29 UTC, merged

2022-11-15 06:39 UTC, Han-Cui commented
Hi, this fix indeed covered more cases which should be detected by the detector. While if I change the test case like this, Spotbugs will give no report, which may be a _false negative_.
```
public class Test2167 {
    public static void test9(boolean someOtherCondition) {
        double y = Double.NaN;
        double k = 10.0;
        while (Double.isNaN(y) && someOtherCondition && k > 0) {
            System.out.println("y before" + y);
            y = Double.parseDouble(System.console().readLine());
            k--;
            System.out.println("y after" + y);
        }
    }
}
```