SEI_CERT_VNA00_J_VNA02_J
spotbugs/spotbugs pull request #2208
Opened 2022-10-11 12:04 UTC by baloghadamsoftware

Introduced detector for rule VNA-00 and VNA-02 with test cases

Introducing new detector for SEI CERT rules:

VNA00-J. Ensure visibility when accessing shared primitive variables
VNA02-J. Ensure that compound operations on shared variables are atomic
The detectors looks for classes that could be part of multithreaded code. This means that the detector only analyzes classes, if either of the following conditions are true for the context of the class:

the class implements the java.lang.Runnable interface (this includes extending the java.lang.Thread class as well, due to transitive cheking for the Runnable interface)
the class contains any synchronized method or block
the class contains any volatile or atomic type variables (the latter means the java.util.concurrent.atomic package)
there is a java.util.concurrent.locks.Lock interface call anywhere in it (lock(), trylock(), unlock())
If any of the above mentioned conditions are present, then the VNA00 detector looks for primitive variables that match all of the following conditions:

the variable gets compared in a not multithreaded method (contains loop conditions as well)
the variable is witten in any method, other then the one it got compared in
the variable is not declared as volatile, nor as an atomic type (java.util.concurrent.atomic package)
there are no manual lock calls in the method where the access is (java.util.concurrent.locks.Lock interface call: lock(), trylock(), unlock())
If any of the above mentioned conditions are present, then the VNA02 detector looks for primitive variables that match all of the following conditions:

the variable gets red in a not secured method
the variable is witten by a compound operation in a not secured method, other then the one it got compared in
the variable is not declared as an atomic type (java.util.concurrent.atomic package), important that volatile is not a guarantee in this rule
there are no manual lock calls in the method where the access is (java.util.concurrent.locks.Lock interface call: lock(), trylock(), unlock())
Note: a method is considered secured, if the following either of the following conditions are true:

the method is snychronized
the method contains any local variables that has an atomic type
the method contains a synchronized block
the method contains any manual lock calls
Both detectors were tested against the code of the following repositories:

RxJava
Jenkins
Spring Framework
I provieded unit tests for each detectors, that covers all possible test cases (multiple types of multithreaded classes, every kind of compund operations for VNA02 etc.).

Although the numbers of the found bugs were high (specially in the case of Jenkins), all bugs seemed to be a possible vulnerability described by the VNA00 or VNA02 rules.

Co-authered-by: @gonczmisi

This PR is a continuation of #2077 (taken over by me) which can be closed.

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [X] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

2022-10-14 00:37 UTC, ThrawnCA approved these changes

2022-10-14 00:37 UTC, ThrawnCA commented on spotbugs/src/main/java/edu/umd/cs/findbugs/detect/CompoundOperationsOnSharedVariables.java
> +            if (stepsMadeInCompoundOperationProcess == 1 && (isReadOpCode(seen) || isPushConstant(seen))) {
Some of this is shared with the previous condition; they could be combined.

2022-10-23 02:37 UTC, KengoTODA requested changes
Please merge the latest upstream branch, to resolve conflicts in the CHANGELOG.

2022-10-23 02:37 UTC, KengoTODA commented on .github/workflows/check-projects.yml
> +        uses: actions/checkout@v2
```suggestion
        uses: actions/checkout@v3
```

2022-10-23 02:37 UTC, KengoTODA commented on .github/workflows/check-projects.yml
> +        uses: actions/checkout@v2
```suggestion
        uses: actions/checkout@v3
```

2022-10-23 02:37 UTC, KengoTODA commented on .github/workflows/check-projects.yml
> +        uses: actions/checkout@v2
```suggestion
        uses: actions/checkout@v3
```

2022-10-23 02:37 UTC, KengoTODA commented on .github/workflows/check-projects.yml
> +            ${{ runner.os }}-gradle-
Java 15 is not supported, better to use Java 17 instead.

```suggestion
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.x'
          cache: 'gradle'
          distribution: 'temurin'
```

2022-10-23 02:37 UTC, KengoTODA commented on .github/workflows/check-projects.yml
> +        uses: actions/upload-artifact@v2
```suggestion
        uses: actions/upload-artifact@v3
```

2022-10-23 02:37 UTC, KengoTODA commented on .github/workflows/check-projects.yml
> +          name: pr
Please give a human-friendly name, or contributors cannot get its meaning.

2022-10-23 02:37 UTC, KengoTODA commented on spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/BadVisibilityOnSharedPrimitiveVariablesTest.java
> +    }
Please reset the property after each test case by `@After`, to keep each test case independent.

2022-10-23 02:37 UTC, KengoTODA commented on .github/workflows/check-projects-comment.yml
> +
Add `permissions` to reduce the privilege of GITHUB_TOKEN.

https://docs.github.com/en/actions/security-guides/automatic-token-authentication

2022-10-23 02:37 UTC, KengoTODA commented on .github/workflows/check-projects.yml
> +
Add `permissions` to reduce the privilege of GITHUB_TOKEN.

https://docs.github.com/en/actions/security-guides/automatic-token-authentication

2022-10-23 02:37 UTC, KengoTODA commented on .github/workflows/check-projects-comment.yml
> +            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data))
Better to use GitHub official CLI to shorten your code:
https://cli.github.com/manual/gh_run_download

2023-03-16 10:43 UTC, baloghadamsoftware commented
@gonczmisi decided to continue the original PR, #2077.

2023-03-16 10:43 UTC, closed without merging