implement reportMissingClass(ClassDescriptor) next to reportMissingClass(ClassNotFoundException)
spotbugs/spotbugs pull request #2234
Opened 2022-10-23 11:12 UTC by kdnakt

Fixed #219

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

2022-10-24 14:03 UTC, KengoTODA requested changes
Classname in spotbugs has two formats: DottedClassName and SlashedClassName. Please use DottedClassNmae to keep new methods consistent with existing methods.

2022-10-25 00:38 UTC, ThrawnCA approved these changes

2022-10-26 01:27 UTC, kdnakt commented on spotbugs/src/main/java/edu/umd/cs/findbugs/BugCollectionBugReporter.java
> +        String missing = classDescriptor.getClassName();
Thanks for the review! I fixed my code.

2022-10-26 01:30 UTC, KengoTODA approved these changes
LGTM, thanks for your contribution!

2022-10-26 01:43 UTC, merged