Unused field not reported due to assumed reflection
spotbugs/spotbugs pull request #2326
Opened 2023-01-23 12:12 UTC by trancexpress

This change ensures an unused field is reported despite assumptions on reflection use for the defining class.

If reflection is assumed, the priority of the created spotbugs problem is lowered.

Fixes: #2325

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [ ] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

2023-01-23 12:12 UTC, trancexpress commented
@iloveeclipse I don't see how to lower the confidence of the bug. Just the priority (++ is lowering it).

2023-01-23 13:49 UTC, iloveeclipse requested changes
Please do two things:
- add a trivial test to spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect
- add an entry to the CHANGELOG.md file

Beside this, I think we should be fine.

Dirty code should be properly reported, and by filtering on prio one can define what one will see what not. 
Not reporting such obvious thing makes people assume that SpotBugs is stupid, which isn't the case in general :-)

2023-01-23 15:59 UTC, iloveeclipse approved these changes
New with "reflective" class usage we report
```
Rank: Of Concern (20), confidence: Low
Pattern: UUF_UNUSED_FIELD
```

Same but **without** "reflective" class usage
```
Rank: Of Concern (18), confidence: Normal
Pattern: UUF_UNUSED_FIELD
```

So one should be able to sort that out.
Thanks, LGTM

2023-01-23 16:00 UTC, merged

2024-10-24 21:18 UTC, vectro commented
With this change, we now generate `SIC_INNER_SHOULD_BE_STATIC_ANON` for these common patterns for getting a `Method` for the current method:
```
        class L {
        };
        Method currentlyExecutingMethod = L.class.getEnclosingMethod();
```
```
        Method currentlyExecutingMethod = new Object(){}.getClass().getEnclosingMethod();
```
The latter also generates `DM_NEW_FOR_GETCLASS`.

Is it worth opening a new issue for that?