test: added a smoke test checking that we can read the XML message files
spotbugs/spotbugs pull request #2676
Opened 2023-11-05 10:19 UTC by gtoison

Check that the XML files are well formed by reading them

2023-11-05 22:37 UTC, ThrawnCA requested changes

2023-11-05 22:37 UTC, ThrawnCA commented on spotbugs-tests/src/test/java/edu/umd/cs/findbugs/LoadMessagesTest.java
> + * FindBugs - Find bugs in Java programs
New files should reference SpotBugs not FindBugs, and the copyright notice should not mention the University of Maryland.

2023-11-06 08:55 UTC, JuditKnoll approved these changes

2023-11-07 23:21 UTC, ThrawnCA approved these changes

2023-11-08 01:14 UTC, merged