Minor cleanup using the ClassName util to convert dotted or slashed
spotbugs/spotbugs pull request #2805
Opened 2024-01-08 11:39 UTC by JuditKnoll

A lot of the times the conversion from dotted to slashed names and wise versa are done on the spot, without much context and adding the annotations. There are already functions for these in the `ClassName` util class. This PR mainly uses these util functions wherever it's possible, and adds the `fromFieldSignatureToDottedClassName()` method to `ClassName`, since the `fromFieldSignature()` and `toDottedClassName()` methods are used together quite frequently.
I didn't add a changelog entry, since I don't think it's necessary.

2024-01-08 11:42 UTC, JuditKnoll commented on spotbugs/src/main/java/edu/umd/cs/findbugs/BugInstance.java
> +                    .collect(Collectors.toList());
This is the only change where it's not only the usage of the method from the ClassName util class, but also removing the unnecessary block and return, and moving the comment.

2024-01-09 01:56 UTC, hazendaz commented
I think due to the size its worth mentioning in a change log just in case something goes wrong users know that it was listed in change log.  It otherwise is ok.

2024-01-09 02:00 UTC, ThrawnCA requested changes

2024-01-09 02:22 UTC, hazendaz commented on spotbugs/src/main/java/edu/umd/cs/findbugs/util/ClassName.java
> +        if (slashedClassName != null) {
That and remove the 'else' all together.  It doesn't allow proper completion when return is within it.  Not a huge deal, we need a large cleanup in general of spotbugs but while at it flip it as noted and remove else as unnecessary then.

2024-01-09 13:38 UTC, JuditKnoll commented on spotbugs/src/main/java/edu/umd/cs/findbugs/ba/AbstractClassMember.java
> +            signature = ClassName.toDottedClassName(signature);
Thanks a lot! Fixed it. I checked it once more, and I couldn't find any other mistakes like this.

2024-01-09 13:42 UTC, JuditKnoll commented on spotbugs/src/main/java/edu/umd/cs/findbugs/util/ClassName.java
> +        if (slashedClassName != null) {
Thanks, fixed it.
I agree, we need a cleanup in spotbugs. I think making it in smaller steps makes it is less overwhelming, easier to reivew and less likely to add issues 😄

2024-01-09 22:26 UTC, ThrawnCA approved these changes

2024-01-09 23:36 UTC, hazendaz approved these changes

2024-01-09 23:36 UTC, merged