Add 'VNA04-J. Ensure that calls to chained methods are atomic' detector with test cases
spotbugs/spotbugs pull request #2986
Opened 2024-05-15 16:14 UTC by PatrikScully

Method chaining allows multiple method calls on the same object in a single statement by having methods return the this reference. This lets the next method call be made on the return value of the previous one. While individual methods can be atomic, the chain itself is not. Therefore, callers must ensure proper locking to guarantee the entire chain of invocations is atomic, as relying on independently atomic methods is not sufficient.

See [https://wiki.sei.cmu.edu/confluence/display/java/VNA04-J.+Ensure+that+calls+to+chained+methods+are+atomic](https://wiki.sei.cmu.edu/confluence/display/java/VNA04-J.+Ensure+that+calls+to+chained+methods+are+atomic)

- [ ] TODO for me: If https://github.com/spotbugs/spotbugs/pull/2919 merged, put the marked methods into a shared utility class

2024-09-23 05:55 UTC, ThrawnCA approved these changes

2024-10-02 16:59 UTC, gtoison approved these changes

2024-10-03 08:09 UTC, JuditKnoll requested changes
Can you please update it to the latest master, where in the meantime some assert functions got introduced to `AbstractIntegrationTest` and use those? I mentioned them at your test util functions.

2024-10-03 08:09 UTC, JuditKnoll commented on spotbugs/src/main/java/edu/umd/cs/findbugs/util/CollectionAnalysis.java
> +    }
Can you please add a comment that it's empty because it's a utility class, so the Sonar analysis won't mark it as problematic?

2024-10-03 08:13 UTC, JuditKnoll commented on spotbugs/src/main/java/edu/umd/cs/findbugs/util/CollectionAnalysis.java
> +package edu.umd.cs.findbugs.util;
Can you please add the SpotBugs license header here?

2024-10-04 07:26 UTC, JuditKnoll requested changes

2024-10-04 07:26 UTC, JuditKnoll commented on spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/ResourceInMultipleThreadsDetectorTest.java
> +        assertBugInMethodAtLine("AT_UNSAFE_RESOURCE_ACCESS_IN_THREAD", "UnsafeFieldUsage", "lambda$new$0", 8);
This line is the same as the previous one.

2024-10-04 08:38 UTC, JuditKnoll approved these changes

2024-10-06 19:50 UTC, hazendaz approved these changes

2024-10-06 19:50 UTC, hazendaz commented
Should we wait on the todo issue to be resolved first (ie get the other PR in ready state and merged before finishing this off?)

2024-10-07 06:02 UTC, JuditKnoll commented
> Should we wait on the todo issue to be resolved first (ie get the other PR in ready state and merged before finishing this off?)

I don't think it's necessary to wait. The todo task is checked, the mentioned methods are moved to utility classes (MethodAnalysis, CollectionAnalysis, and some into MutableClasses) in both PRs, so they don't rely on each other anymore.

2024-10-09 05:18 UTC, merged