Avoid exception when inspecting empty switch statements
spotbugs/spotbugs pull request #2996
Opened 2024-05-24 23:57 UTC by zbynek

Fixes #2995 

The testcase reproduces the issue, at least with Java 11. For the fix itself I'm not 100% sure it's the right approach

2024-05-26 05:44 UTC, gtoison commented
Thanks for the PR! I have approved the run but spotless failed the build. Can you please run this and commit the changes?
gradlew spotlessApply

2024-05-26 15:38 UTC, gtoison requested changes
Aside from the small comment can you please add a new entry in the [changelog](https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md)?
Thank you very much for the fix!

2024-05-26 15:38 UTC, gtoison commented on spotbugs/src/main/java/edu/umd/cs/findbugs/SwitchHandler.java
> +        public int getLastOffset() {
Can you please make this method private?

2024-05-26 23:29 UTC, ThrawnCA approved these changes

2024-05-27 04:55 UTC, gtoison approved these changes

2024-05-27 18:07 UTC, merged