Removed log4j2 prefer() dependency constraint
spotbugs/spotbugs pull request #3006
Opened 2024-06-06 19:49 UTC by gtoison

The constraint causes gradle to add log4j-core-2.22.0.jar and log4j-core-2.23.1.jar to the distribution.
Removed the constraint so only the latter version is included.

2024-06-06 23:09 UTC, hazendaz approved these changes

2024-06-06 23:43 UTC, merged

2024-12-21 00:29 UTC, stu3139 approved these changes

2024-12-21 00:39 UTC, stu3139 approved these changes

2024-12-21 00:40 UTC, stu3139 requested changes
Compatibility