RocksDB ReadOptions not recognized as closeable
spotbugs/spotbugs pull request #3076
Opened 2024-08-11 12:39 UTC by gtoison

The code in `BuildObligationPolicyDatabase` initializes obligations to close for some classes such as `java.sql.Resultset` or `java.io.FileInputStream` but other classes implementing `AutoCloseable` are not handled as noted in #3069 .

2024-08-12 06:17 UTC, gtoison commented
We probably want to raise a warning for every unclosed Autocloseable at some point but the current code tries to do a bit more, for instance keeping track that a ResultSet is closed when its Connection is closed. 

I've added a built-in database that only contains entries for RocksDB ReadOptions

2024-08-12 09:19 UTC, JuditKnoll requested changes

2024-08-13 15:35 UTC, gtoison commented on spotbugs-tests/src/test/java/edu/umd/cs/findbugs/ba/Issue3069Test.java
> +public class Issue3069Test extends AbstractIntegrationTest {
Done, thanks!

2024-08-13 15:38 UTC, gtoison commented on spotbugsTestCases/src/fakeLibraries/org/rocksdb/AbstractImmutableNativeReference.java
I was a bit concerned that if we start accumulating dependencies we will have problems with transitive dependencies conflicts. I suppose that another way would be to add  sample projects but that would also make the build more complicated.
I thought it was an acceptable tradeoff but please let me know if you think otherwise

2024-08-13 17:15 UTC, JuditKnoll commented on spotbugsTestCases/src/fakeLibraries/org/rocksdb/AbstractImmutableNativeReference.java
No, you are right, I was just thinking where should we draw the line in connection with this.

2024-08-13 17:15 UTC, JuditKnoll approved these changes

2024-08-16 04:04 UTC, ThrawnCA approved these changes

2024-08-29 19:10 UTC, merged